import { ROUTES } from "./definitions";

/**
 * Unified source of truth for Role-Based Access Control (RBAC) across the frontend.
 * This ensures that the AppRoutes and the AppSidebar always enforce the exact same permissions.
 */
export const ROLES = {
  ADMIN: "Admin",
  MANAGER: "Manager",
  CASHIER: "Cashier",
  USER: "User",
} as const

export const ROUTE_PERMISSIONS: Record<string, string[]> = {
  [ROUTES.DASHBOARD]: [ROLES.ADMIN, ROLES.MANAGER, ROLES.CASHIER],
  [ROUTES.LOGIN]: [],
  [ROUTES.USERS]: [ROLES.ADMIN],
  [ROUTES.PRODUCTS]: [ROLES.ADMIN, ROLES.MANAGER, ROLES.CASHIER, ROLES.USER],
  [ROUTES.CATEGORIES]: [ROLES.ADMIN, ROLES.MANAGER, ROLES.CASHIER],
  [ROUTES.SUPPLIERS]: [ROLES.ADMIN, ROLES.MANAGER],
  [ROUTES.CUSTOMERS]: [ROLES.ADMIN, ROLES.MANAGER, ROLES.CASHIER],
  [ROUTES.GOOD_RECEIPT]: [ROLES.ADMIN, ROLES.MANAGER, ROLES.CASHIER],
  [ROUTES.SALES_ORDERS]: [ROLES.ADMIN, ROLES.MANAGER, ROLES.CASHIER],
  [ROUTES.INVENTORY_MOVEMENTS]: [ROLES.ADMIN, ROLES.MANAGER, ROLES.CASHIER,],
  [ROUTES.STOCK_ADJUSTMENTS]: [ROLES.ADMIN, ROLES.MANAGER],
  [ROUTES.BREAK_PACKS]: [ROLES.ADMIN, ROLES.MANAGER],
  [ROUTES.INVOICES]: [ROLES.ADMIN, ROLES.MANAGER,],
  [ROUTES.PAYMENTS]: [ROLES.ADMIN, ROLES.MANAGER],
  [ROUTES.PRICE_HISTORY]: [ROLES.ADMIN, ROLES.MANAGER, ROLES.CASHIER],
  [ROUTES.REORDERS]: [ROLES.ADMIN, ROLES.MANAGER, ROLES.CASHIER],
  [ROUTES.REPORTS_POPULAR]: [ROLES.ADMIN, ROLES.MANAGER, ROLES.CASHIER],
  [ROUTES.REPORTS_PROFIT]: [ROLES.ADMIN, ROLES.MANAGER],
  [ROUTES.REPORTS_NO_SALES]: [ROLES.ADMIN, ROLES.MANAGER, ROLES.CASHIER],
  [ROUTES.PRICE_MANAGER]: [ROLES.ADMIN, ROLES.MANAGER],
  settings: [ROLES.ADMIN, ROLES.MANAGER],
};

export function hasRole(role: string, allowedRoles: string[]) {
  return allowedRoles.includes(role)
}